config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from account import views
from config import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^pjs1234', views.pjs1234),
    url(r'^$', views.login_site, name='login_site'),
    url(r'^server/', views.server, name='server'),
    url(r'^signup', views.signUo, name='signup'),
    url(r'^logout', views.logout_site, name='logout_site'),
    url(r'^design_data/', include('design_data.urls', namespace='design_data')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^setting/', include('setting.urls', namespace='setting')),
    url(r'^material/', include('materials.urls', namespace='material')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^machine/', include('machine.urls', namespace='machine')),
    url(r'^production/', include('production.urls', namespace='production')),
    #url(r'^ordercheack$', views.ordercheack),
]



urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

machine/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from machine import views
from rest_framework import routers
app_name = 'machine'

router4 = routers.DefaultRouter()
router4.register(r'knit_machine', views.Knit_machine_api, basename='knit_machine_apis')
router5 = routers.DefaultRouter()
router5.register(r'warp_machine', views.Warp_machine_api, basename='warp_machine_apis')

urlpatterns = [
    url(r'^$', csrf_exempt(views.showMachine)),
    url(r'^setmachine$', csrf_exempt(views.setMachine)),
    url(r'^listByType$', csrf_exempt(views.listByType)),
    url(r'^getWarpInfoByJson$', csrf_exempt(views.getWarpInfoByJson)),
    url(r'^getKnitInfoByJson$', csrf_exempt(views.getKnitInfoByJson)),
    url(r'^setKnitMachine$', csrf_exempt(views.setKnitMachine)),
    url(r'^setWarpMachine$', csrf_exempt(views.setWarpMachine)),
    url(r'^deleteWarpMachine$', csrf_exempt(views.deleteWarpMachine)),
    url(r'^deleteKnitMachine$', csrf_exempt(views.deleteKnitMachine)),
    url(r'^knit_machine_api/', include(router4.urls, 'knit_machine_api'), name='knit_machine_api'),
    url(r'^warp_machine_api/', include(router5.urls, 'warp_machine_api'), name='warp_machine_api'),
    #url(r'^ordercheack$', views.ordercheack),
]

order/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from . import views
from rest_framework import routers

app_name = 'order'

router = routers.DefaultRouter()
router.register(r'order_design_data', views.Order_design_data_api, basename='order_design_data_apis')
router1 = routers.DefaultRouter()
router1.register(r'order_data', views.Order_api, basename='order_data_apis')

urlpatterns = [
    url(r'^rawroll/(?P<id>\d+)', views.rawroll),
    url(r'^warpWorkSheet/(?P<id>\d+)', views.warpTable),
    url(r'^modify$', views.modifyOrder),
    url(r'^delete$', views.delete),
    url(r'^$', views.order),
    url(r'^list$', views.getOrderListByJson),
    url(r'^detail/(?P<orderId>\d+)', views.getOrderByJson),
    url(r'^style_detail/(?P<orderId>\d+)$', views.getstyleByJson),
    url(r'^style_modify/(?P<orderId>\d+)$', views.Style_modify),
    url(r'^style_suc/(?P<orderId>\d+)$', views.Style_suc),
    # url(r'^change_style/(?P<orderId>\d+)$', views.changeStyleck),
    url(r'^showQr/(?P<id>\d+)', views.showQr),
    url(r'^subOrderJson/(?P<id>\d+)', views.getSubOrderByJson),
    url(r'^ordercheack$', views.ordercheack),
    url(r'^design_api/', include(router.urls, 'Order_design'), name='design_api'),
    url(r'^order_api/', include(router1.urls, 'Order'), name='order_api'),
    url(r'^order_end/', views.order_end, name='order_end'),
]

setting/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'design_data'
urlpatterns = [
    url(r'^activeUser$', views.activeUser),
    url(r'^companyInfo$', views.companyInfo),
    url(r'^changePassword$', views.changePassword),
    url(r'^changeUserInfo$', views.changeUserInfo),
    url(r'^getAddress', views.getAddress),
    url(r'^userdetailtest/(?P<id>\d+)$', views.usetdetailtest),
    url(r'^userupdate$', views.userupdates),
    url(r'^userdel$', views.userdel),
    url(r'^accountadd$',views.accountadd),
    url(r'^accountselect$', views.accountselect),
    url(r'^accountmodify$', views.accountmodify),
    url(r'^accountdel$',views.accountdel),
    url(r'^languagech$',views.langch),
    url(r'^', csrf_exempt(views.setting)),
]

design_data/models.py
from django.db import models


def upload_product_file(instance, filename):
    return filename


class FSTY_CAD_Design_Data(models.Model):
    CAD_Design_Data_id = models.AutoField(primary_key=True)
    CAD_Design_Data_name = models.CharField(max_length=100, null=True)
    CAD_Design_Data_code = models.CharField(max_length=100, null=True)
    CAD_Design_Data_xml = models.FileField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_pattern_image = models.ImageField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_simulation_image = models.ImageField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_create_date = models.DateTimeField(auto_now_add=True, blank=True)
    CAD_Design_Data_trc_file = models.FileField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_magnification = models.CharField(max_length=10, null=True, blank=True)
    Linkage_code = models.CharField(max_length=5000, null=True, default=None)

    class Meta:
        db_table = 'FSTY_CAD_Design_Data'

    def __str__(self):
        return self.CAD_Design_Data_name


class FSTY_CAD_Production(models.Model):
    CAD_Production_id = models.AutoField(primary_key=True)
    CAD_Production_quota_per_day = models.CharField(max_length=100, null=True)
    CAD_Production_machine_name = models.CharField(max_length=100, null=True)
    CAD_Production_note = models.CharField(max_length=100, null=True)
    CAD_Production_design_data = models.OneToOneField(FSTY_CAD_Design_Data, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Production'


class FSTY_CAD_Fabric(models.Model):
    CAD_Fabric_id = models.AutoField(primary_key=True)
    fabric_type = (
        ('R', u'row'),
        ('S', u'simulated')
    )
    CAD_Fabric_type = models.CharField(max_length=1, choices=fabric_type, null=True)
    CAD_Fabric_wpi = models.CharField(max_length=100, null=True)
    CAD_Fabric_cpi = models.CharField(max_length=100, null=True)
    CAD_Fabric_width = models.CharField(max_length=100, null=True)
    CAD_Fabric_weight_per_width = models.CharField(max_length=100, null=True)
    CAD_Fabric_production = models.ForeignKey(FSTY_CAD_Production, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Fabric'


class FSTY_CAD_Layer(models.Model):
    CAD_Layer_id = models.AutoField(primary_key=True)
    CAD_Layer_name = models.CharField(max_length=100, null=True)
    CAD_Layer_ratio = models.CharField(max_length=100, null=True)
    CAD_Layer_mm_rack = models.CharField(max_length=100, null=True)
    CAD_Layer_use = models.CharField(max_length=100, null=True)
    CAD_Layer_beam = models.CharField(max_length=100, null=True)
    CAD_Layer_total = models.CharField(max_length=100, null=True)
    CAD_Layer_iodata = models.CharField(max_length=2000, null=True)
    CAD_Layer_design_data = models.ForeignKey(FSTY_CAD_Design_Data, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Layer'


class FSTY_CAD_Yarn(models.Model):
    CAD_Yarn_id = models.AutoField(primary_key=True)
    CAD_Yarn_idx = models.CharField(max_length=100, null=True)
    CAD_Yarn_maker = models.CharField(max_length=100, null=True)
    CAD_Yarn_spec = models.CharField(max_length=100, null=True)
    CAD_Yarn_code = models.CharField(max_length=100, null=True)
    CAD_Yarn_rgb_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_lab_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_pantone_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_layer = models.OneToOneField(FSTY_CAD_Layer, on_delete=models.CASCADE, null=True)


    class Meta:
        db_table = 'FSTY_CAD_Yarn'


class FSTY_CAD_Chain_Link(models.Model):
    CAD_Chain_Link_id = models.AutoField(primary_key=True)
    CAD_Chain_Link_course = models.CharField(max_length=2000)
    CAD_Chain_Link_layer = models.OneToOneField(FSTY_CAD_Layer, on_delete=models.CASCADE, null=True)


    class Meta:
        db_table = 'FSTY_CAD_Chain_Link'

machine/models.py
from django.db import models

# Create your models here.
from account.models import Company


class Warp_Machine(models.Model):
    tns_code = models.CharField(max_length=50, null=True)
    user_id = models.CharField(max_length=50, null=True) #작업자는 항상 변경됨
    company_code = models.CharField(max_length=50, null=True) #User에 존재함
    tws_name = models.CharField(max_length=50, null=True)
    tws_installation_time = models.DateTimeField(null=True) #등록시간으로 사용하겠음. Ver.영우
    tws_ip = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'Warp_Machine'


class Knit_Machine(models.Model):
    tns_code = models.CharField(max_length=50, null=True)
    user_id = models.CharField(max_length=50, null=True)
    company_code = models.CharField(max_length=50, null=True)
    trs_installation_time = models.DateTimeField(null=True)
    trs_model_name = models.CharField(max_length=50, null=True)
    trs_beam_cnt = models.IntegerField(null=True)
    trs_bar_cnt = models.IntegerField(null=True)
    trs_rpm_main = models.IntegerField(null=True)
    trs_eac_enable = models.IntegerField(null=True)
    trs_tempo = models.IntegerField(null=True)
    trs_lowmotor_enable = models.IntegerField(null=True)
    trs_gauge = models.IntegerField(null=True)
    trs_ip = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'Knit_Machine'



class YW_Knit_Machine(models.Model):
    name = models.CharField(max_length=50, null=True)
    code = models.CharField(max_length=50, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    create_data = models.DateTimeField(auto_now_add=True)
    rpm = models.IntegerField(null=True)
    gauge = models.IntegerField(null=True)
    bar_cnt = models.IntegerField(null=True)

    class Meta:
        db_table = 'yw_knit_machine'


class YW_Warp_Machine(models.Model):
    name = models.CharField(max_length=50, null=True)
    code = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        db_table = 'yw_warp_machine'

production/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

from order.models import Order_DesignData
from machine.models import Knit_Machine, Warp_Machine, YW_Knit_Machine, YW_Warp_Machine
from materials.models import Beam, Yarn

# Create your models here.
class Knit_Process(models.Model):
    order_designdata = models.OneToOneField(Order_DesignData, on_delete=models.CASCADE)
    knit_machine_id = models.ForeignKey(Knit_Machine, related_name='knit_machine_code', null=True, on_delete=models.CASCADE)
    yw_knit_machine_id = models.ForeignKey(YW_Knit_Machine, null=True, on_delete=models.CASCADE)
    start_time = models.DateTimeField(null=True, default=None)
    end_time = models.DateTimeField(null=True, default=None)
    real_start_time = models.DateTimeField(null=True, default=None)
    real_end_time = models.DateTimeField(null=True, default=None)
    #beam = models.ForeignKey(Beam, null=True)

    class Meta:
        db_table = 'Knit_Process'


class Knit_Beam(models.Model):
    knit_process = models.ForeignKey(Knit_Process, on_delete=models.CASCADE)
    beam = models.ForeignKey(Beam, on_delete=models.CASCADE)
    knit_external = models.IntegerField(null=True)
    knit_current_external = models.IntegerField(null=True)
    knit_turn_cnt = models.IntegerField(null=True)
    knit_current_turn_cnt = models.IntegerField(null=True)
    knit_yarn_thick = models.IntegerField(null=True)
    #knit_yarn = models.ForeignKey(Yarn, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'Knit_Beam'


class Warp_Process(models.Model):
    order_designdata = models.OneToOneField(Order_DesignData, on_delete=models.CASCADE)
    warp_machine_id = models.ForeignKey(Warp_Machine, null=True, on_delete=models.CASCADE)
    yw_warp_machine_id = models.ForeignKey(YW_Warp_Machine, null=True, on_delete=models.CASCADE)
    start_time = models.DateTimeField(null=True, default=None)
    end_time = models.DateTimeField(null=True, default=None)
    real_start_time = models.DateTimeField(null=True, default=None)
    real_end_time = models.DateTimeField(null=True, default=None)

    #beam = models.ForeignKey(Warp_Beam, null=True)

    class Meta:
        db_table = 'Warp_Process'


class Warp_Beam(models.Model):
    warp_process = models.ForeignKey(Warp_Process, on_delete=models.CASCADE) #스케쥴 FK
    beam = models.ForeignKey(Beam, on_delete=models.CASCADE) #공빔 FK
    external = models.IntegerField(null=True) #실 감겨진 상태의 둘레
    current_external = models.IntegerField(null=True) # 현재 빔 둘레
    turn_cnt = models.IntegerField(null=True) # 생산 후 처음 회전수
    current_turn_cnt = models.IntegerField(null=True) #현재 잔량 회전수
    yarn_thick = models.IntegerField(null=True) #정경된 실두꼐 (외경 - 내경) / 턴수
    yarn_count = models.IntegerField(null=True) #실가락수 (정경본수)
    yarn_meter = models.IntegerField(null=True) #감겨진 실의 길이
    yarn_current_meter = models.IntegerField(null=True) #사용 이후 잔량 실 길이
   #yarn = models.ForeignKey(Yarn, on_delete=models.CASCADE, null=True) #실 FK


    class Meta:
        db_table = 'Warp_Beam'


class Knit_Machine_Realtime(models.Model):
    knit_process = models.ForeignKey(Knit_Process, null=True, on_delete=models.CASCADE)
    trs_operation_number = models.IntegerField(null=True)
    trs_total_run_course = models.IntegerField(null=True)
    trs_state = models.IntegerField(null=True)
    trs_stopmark = models.IntegerField(null=True)
    trs_onetime_prdt = models.IntegerField(null=True)
    trs_set_prdt = models.IntegerField(null=True)
    trs_run_course = models.IntegerField(null=True)
    trs_total_oper_time = models.DateTimeField(null=True)
    trs_total_accum_time = models.DateTimeField(null=True)
    trs_meter = models.FloatField(null=True)
    trs_total_meter = models.IntegerField(null=True)
    trs_accumulate_meter = models.IntegerField(null=True)
    trs_key_angle = models.IntegerField(null=True)
    trs_rpm_main = models.IntegerField(null=True)
    trs_sensor_01 = models.IntegerField(null=True)
    trs_sensor_02 = models.IntegerField(null=True)
    trs_sensor_03 = models.IntegerField(null=True)
    trs_sensor_04 = models.IntegerField(null=True)
    trs_sensor_05 = models.IntegerField(null=True)
    trs_sensor_06 = models.IntegerField(null=True)
    trs_sensor_07 = models.IntegerField(null=True)
    trs_sensor_08 = models.IntegerField(null=True)
    trs_sensor_09 = models.IntegerField(null=True)
    trs_sensor_10 = models.IntegerField(null=True)
    trs_onoff = models.CharField(max_length=10, null=True)

    class Meta:
        db_table = 'Knit_Machine_Realtime'


class Warp_Machine_Realtime(models.Model):
    warp_process = models.ForeignKey(Warp_Process, null=True, on_delete=models.CASCADE)
    tws_start_date = models.DateTimeField(null=True)
    tws_start_time = models.DateTimeField(null=True)
    tws_meter = models.IntegerField(null=True)
    tws_state = models.IntegerField(null=True)
    tws_hoist_state = models.IntegerField(null=True)
    tws_oiling_state = models.IntegerField(null=True)
    tws_clamp_state = models.IntegerField(null=True)
    tws_w_inverter_state = models.IntegerField(null=True)
    tws_s_inverter_state = models.IntegerField(null=True)
    tws_c_inverter_state = models.IntegerField(null=True)
    tws_current_turncnt = models.IntegerField(null=True)
    tws_runtime = models.DateTimeField(null=True)
    tws_current_meter = models.IntegerField(null=True)
    tws_kia = models.IntegerField(null=True)
    tws_warper_speed = models.FloatField(null=True)
    tws_warper_outside = models.IntegerField(null=True)
    tws_warper_total_length = models.FloatField(null=True)
    tws_creel_total_length = models.IntegerField(null=True)
    tws_creel_speed = models.IntegerField(null=True)
    tws_elongation_rate = models.IntegerField(null=True)
    tws_relax_deviation = models.IntegerField(null=True)
    tws_error = models.DateTimeField(null=True)
    tws_onoff = models.CharField(max_length=10, null=True)

    class Meta:
        db_table = 'Warp_Machine_Realtime'


setting/models.py
from django.db import models

# Create your models here.

templates/designDetail.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block staticfile %}
<link rel="stylesheet" href="{% static 'css/design.css' %}">
<script type="text/javascript" src="{% static 'js/design.js' %}"></script>
<script type="text/javascript">
lang_code = {{ userlang.lang_code }};
    const lang = {
        ko:{
            warpplan:"경 편 설 계 도", yarnnumber:"사번", yarnmaker:"원사메이커", yarntype:"사종", color:"색상", uniquecode:"고유코드",
            ratio:"비율(%)", transmission:"송출(mm/rack)", boncount:"본수", beamcount:"빔수", totalboncount:"총 본수", fabric:"원단",
            waledensity:"웨일밀도", coursedensity:"코스밀도", width:"폭", weightwidth:"중량/폭", arrangement:"배열", remark:"비고",
            weavechart:"조직도", magnification:"배율 : ", processingpaper:"가공지", greige:"생지"

        },
        en:{
            warpplan:"Warp plan chart", yarnnumber:"Yarn number", yarnmaker:"Yarn maker", yarntype:"Yarn type", color:"Color",
            uniquecode:"unique code", ratio:"ratio(%)", transmission:"transmission(mm/rack)", boncount:"bon count", beamcount:"beam count",
            totalboncount:"total bon count", fabric:"Fabric", waledensity:"Wake density", coursedensity:"Course density", width:"Width",
            weightwidth:"Weight/Width", arrangement:"Arrangement", remark:"Remark", weavechart:"Weave chart", magnification:"Magnification : ",
            processingpaper:"processing paper", greige:"Greige"
        }
    };
    // 언어별 렌더링
    function render(locale) {
        const $lang = document.querySelectorAll("[data-lang]");
        $lang.forEach(el => {
            const code = el.dataset.lang;
            el.textContent = lang[locale][code]
        })
    };
    if(lang_code==0){
        render("ko");
    };
    if(lang_code==1){
        render("en");
    };
</script>
{% endblock staticfile %}

{% block content %}
            <div id="orderContentWrap" class="fix">
                <div id="showDesingData">
                    <div id="designData">
                        <div id="orderWrap">
                            <h2 data-lang="warpplan">[warpplan]</h2>
                            <div id="designName">Name : {{ object.CAD_Design_Data_name }}</div>
                            <div id="topSecond">
                                <div id="designCode">CODE : {{ object.CAD_Design_Data_code }}</div>
                                <div id="date">DATE : {{ object.CAD_Design_Data_create_date|date:"Y-m-d" }}</div>
                            </div>
                            <div id="yarnDiv">
                                <div></div>
                                <table id="yarnTable">
                                <colgroup>
                                    <col width="5%">
                                    <col width="5%">
                                    <col width="10%">
                                    <col width="13%">
                                    <col width="7%">
                                    <col width="10%">
                                    <col width="10%">
                                    <col width="15%">
                                    <col width="10%">
                                    <col width="5%">
                                    <col width="10%">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>BAR</th>
                                        <th data-lang="yarnnumber">[yarnnumber]</th>
                                        <th data-lang="yarnmaker">[yarnmaker]</th>
                                        <th data-lang="yarntype">[yarntype]</th>
                                        <th data-lang="color">[color]</th>
                                        <th data-lang="uniquecode">[uniquecode]</th>
                                        <th data-lang="ratio">[ratio]</th>
                                        <th data-lang="transmission">[transmission]</th>
                                        <th data-lang="boncount">[boncount]</th>
                                        <th data-lang="beamcount">[beamcount]</th>
                                        <th data-lang="totalboncount">[totalboncount]</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for layer in object.fsty_cad_layer_set.all %}
                                    <tr>
                                        <td>{{ layer.CAD_Layer_name }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_idx }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_maker }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_spec }}</td>
                                        <td><div class="cadyarn_color" style="background-color:rgb({{ layer.fsty_cad_yarn.CAD_Yarn_rgb_color }}); width:80%; height:15px; border: 1px solid black;"></div></td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_code }}</td>
                                        <td>{{ layer.CAD_Layer_ratio }}</td>
                                        <td>{{ layer.CAD_Layer_mm_rack }}</td>
                                        <td>{{ layer.CAD_Layer_use }}</td>
                                        <td>{{ layer.CAD_Layer_beam }}</td>
                                        <td>{{ layer.CAD_Layer_total }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </div>
                            <div id="fabricDiv">
                                <div></div>
                                <table id="fabricTable">
                                <colgroup>
                                    <col width="20%">
                                    <col width="20%">
                                    <col width="20%">
                                    <col width="20%">
                                    <col width="20%">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th data-lang="fabric">[fabric]</th>
                                        <th data-lang="waledensity">[waledensity]</th>
                                        <th data-lang="coursedensity">[coursedensity]</th>
                                        <th data-lang="width">[width]</th>
                                        <th data-lang="weightwidth">[weightwidth]</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for fabric in object.fsty_cad_production.fsty_cad_fabric_set.all %}
                                    <tr>
                                        {% if fabric.CAD_Fabric_type == 'R' %}<td data-lang="greige">[greige]</td>{% else %}<td data-lang="processingpaper">[processingpaper]</td>{% endif %}
                                        <td>{{ fabric.CAD_Fabric_wpi }} w/inch</td>
                                        <td>{{ fabric.CAD_Fabric_cpi }} c/cm</td>
                                        <td>{{ fabric.CAD_Fabric_width }} inch</td>
                                        <td>{{ fabric.CAD_Fabric_weight_per_width }} g/y</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </div>
                            <div id="colorDiv">
                                <div></div>
                                <table id="colorTable">
                                <colgroup>
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>BAR</th>
                                        <th>RGB Color</th>
                                        <th>LAB Color</th>
                                        <th>Pantone Color</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for layer in object.fsty_cad_layer_set.all %}
                                    <tr>
                                        <td>{{ layer.CAD_Layer_name }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_rgb_color }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_lab_color }}</td>
                                        <td>{{ layer.fsty_cad_yarn.CAD_Yarn_pantone_color }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </div>
                            <div id="layerDiv">
                                <div></div>
                                <table id="layerTable">
                                <colgroup>
                                    <col width="10%">
                                    <col width="90%">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>BAR</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for layer in object.fsty_cad_layer_set.all %}
                                    <tr>
                                        <td>{{ layer.CAD_Layer_name }}</td>
                                        <td>{{ layer.fsty_cad_chain_link.CAD_Chain_Link_course }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </div>
                            <div id="productionDiv">
                                <div></div>
                                <table id="productionTable">
                                    <colgroup>
                                        <col width="20%">
                                        <col width="80%">
                                    </colgroup>
                                    <thead>
                                        <tr>
                                            <th colspan="2">Production</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td data-lang="magnification">[magnification]</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td data-lang="remark">[remark]</td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table id="imgTable">
                                    <colgroup>
                                        <col width="50%">
                                        <col width="50%">
                                    </colgroup>
                                    <thead>
                                        <tr>
                                            <th data-lang="weavechart">[weavechart]</th>
                                            <th data-lang="magnification">[magnification]</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><div style="background-image: url('/media/{{ object.CAD_Design_Data_pattern_image }}')"></div></td>
                                            <td><div style="background-image: url('/media/{{ object.CAD_Design_Data_simulation_image }}')"></div></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock content %}

templates/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Knit Total System</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script src="{% static 'js/dytec_send' %}"></script>
</head>
<body>
<div id="loginWrap">
    <div id="loginBox">
        <h1>Knit Total System</h1>
        <div id="loginTab">
            <form action="/signup" method="POST" name="signUpForm" id="signUpForm">
            <div id="loginInputBox">
                {% csrf_token %}
                    {{ form.as_p }}
                <div class="loginBtn">
                    <input id="signupBtn" type="submit" value="Sign Up">
                </div>
            </div>
            </form>
            <div class="rightDeco">
                <div class="decorationLBar"></div>
                <div class="decorationSBar"></div>
            </div>
            <div class="leftDeco">
                <div class="decorationLBar"></div>
                <div class="decorationSBar"></div>
            </div>
        </div>
    </div>
</div>

</body>
</html>